modLoader="javafml"
loaderVersion="[47,)"
license="Custom license"

[[mods]]
modId="crystalcaves"
version="1.0.0.2"
displayName="CrystalCaves"
displayURL="https://modrinth.com/mod/crystalcaves"
logoFile="logo.png"
credits="Made by OmgRod using MCreator"
authors="OmgRod"
description="Adds Crystalite caves, ores, armor and tools"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.crystalcaves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



