modLoader="javafml"
loaderVersion="[2,)"
license="Custom license"

[[mods]]
modId="crystalcaves"
version="1.0.0"
displayName="CrystalCaves"
displayURL="https://modrinth.com/mod/crystalcaves"
logoFile="logo.png"
credits="Made by OmgRod using MCreator"
authors="OmgRod"
description="Adds Crystalite caves, ores, armor and tools"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.crystalcaves]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.crystalcaves]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



